language: node_js
node_js:
    - 16
install:
    - yarn install # npm ci
    - yarn add vuepress
    # - yarn build
script:
    - chmod u+x deploy.sh
    - bash ./deploy.sh

    #- yarn add vuepress
    #- yarn docs:build # npm run docs:build
#deploy:
#provider: pages
#skip_cleanup: true
#local_dir: my-blog/.vuepress/dist
#github_token: 74345f78d64e00640616eb450f94f17847311241
# 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
#keep_history: true
#on:
#branch: master
branch: master
